GET http://localhost:2000/api/dogs

###

POST http://localhost:2000/api/dogs
Content-Type: application/json

{
  "name": "Hebbe",
  "age": 13,
  "breed": "Cocker-Spaniel",
  "color": "orange",
  "id": 1
}